Attendance.Web/Controllers/CardGroupItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Attendance.Core.Code;
using Attendance.Models;
using Attendance.Models.Entities;
using Attendance.Web.Services.Errors;

namespace Attendance.Web.Controllers
{
    public class CardGroupItemsController : Controller
    {
        private DatabaseContext db = new DatabaseContext();
        private IErrorService _errors;
        public CardGroupItemsController()
        {
            _errors = new ErrorService();
        }
        // GET: CardGroupItems
        public ActionResult Index(Guid? id)
        {
            ViewBag.GroupId = id;
            var groupItems = db.GroupItems.Where(g=>g.GroupId ==id).Include(c => c.Group).Where(c=>c.IsDeleted==false).OrderByDescending(c=>c.CreationDate);
            return View(groupItems.ToList());
        }

        // GET: CardGroupItems/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardGroupItem cardGroupItem = db.GroupItems.Find(id);
            if (cardGroupItem == null)
            {
                return HttpNotFound();
            }
            return View(cardGroupItem);
        }


        public ActionResult SubGroups(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var cardGroupItems = db.GroupItems.Where(x=>x.ParentGroupId == id.Value);
            var group = db.GroupItems.Find(id);
            ViewBag.GroupId = id;
            return View(cardGroupItems);
        }

        public ActionResult AddSubGroup(Guid parentId)
        {
            var group = db.GroupItems.FirstOrDefault(x => x.Id == parentId);

            ViewBag.ParentGroupId = new SelectList(db.GroupItems.Where(g=>g.Id == group.GroupId),
                "Id", "Title", group);
            ViewBag.IsParent = true;
            return View();
        }

        // GET: CardGroupItems/Create
        public ActionResult Create(Guid groupId)
        {
            var group = db.Groups.FirstOrDefault(x=>x.Id == groupId);
            
                ViewBag.GroupId = new SelectList(db.Groups, "Id", "Title", group);
                ViewBag.IsParent = true;
                return View(); 
        }



        // POST: CardGroupItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CardGroupItem cardGroupItem)
        {
            if (ModelState.IsValid)
            {
				cardGroupItem.IsDeleted=false;
				cardGroupItem.CreationDate= DateTime.Now; 
					
                cardGroupItem.Id = Guid.NewGuid();
                db.GroupItems.Add(cardGroupItem);
                db.SaveChanges();
                return RedirectToAction("Index",new { id = cardGroupItem.GroupId});
            }

            ViewBag.GroupId = new SelectList(db.Groups, "Id", "Title", cardGroupItem.GroupId);
            return View(cardGroupItem);
        }

        // GET: CardGroupItems/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardGroupItem cardGroupItem = db.GroupItems.Find(id);
            if (cardGroupItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupId = new SelectList(db.Groups, "Id", "Title", cardGroupItem.GroupId);

            return View(cardGroupItem);
        }

        // POST: CardGroupItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,GroupId,IsActive,CreationDate,LastModifiedDate,IsDeleted,DeletionDate,Description")] CardGroupItem cardGroupItem)
        {
            if (ModelState.IsValid)
            {
				cardGroupItem.IsDeleted=false;
					cardGroupItem.LastModifiedDate=DateTime.Now;
                db.Entry(cardGroupItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = cardGroupItem.GroupId });
            }
            ViewBag.GroupId = new SelectList(db.Groups, "Id", "Title", cardGroupItem.GroupId);
            return View(cardGroupItem);
        }

        // GET: CardGroupItems/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardGroupItem cardGroupItem = db.GroupItems.Find(id);
            if (cardGroupItem == null)
            {
                return HttpNotFound();
            }
            return View(cardGroupItem);
        }

        // POST: CardGroupItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            CardGroupItem cardGroupItem = db.GroupItems.Find(id);
			cardGroupItem.IsDeleted=true;
			cardGroupItem.DeletionDate=DateTime.Now;
 
            db.SaveChanges();
            return RedirectToAction("Index", new { id = cardGroupItem.GroupId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult GroupItemCards(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardGroupItem cardGroupItem = db.GroupItems.Find(id);
            if (cardGroupItem == null)
            {
                return HttpNotFound();
            }
            var cards = cardGroupItem.GroupItemCards.Select(c => c.Card).Distinct().ToList();
            ViewBag.cardGroupTitle = cardGroupItem.Title;
            ViewBag.cardGroupItemId = cardGroupItem.Id;
            return View(cards);
        }

        public ActionResult CardStatus(Guid itemId,bool status)
        {
            var id = itemId;
            if (itemId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardGroupItem cardGroupItem = db.GroupItems.Find(id);
            if (cardGroupItem == null)
            {
                return HttpNotFound();
            }
            try
            {
                var statusStr = status ? "فعال" : "غیرفعال ";
                TempData["Toastr"] = new ToastrViewModel() { Class = "success", Text = "عملیات با موفقیت انجام شد" };
                cardGroupItem.GroupItemCards.Select(c => c.Card).Distinct().ToList().ForEach(c => {
                    c.IsActive = status;
                    db.Entry(c).State = EntityState.Modified;
                    db.CardStatusHistories.Add(new CardStatusHistory()
                    {
                        Card =c,
                        CardId = c.Id,
                        Id=Guid.NewGuid(),
                        CreationDate=DateTime.Now,
                        IsActive = true,
                        Description=$"بصورت گروهی {statusStr} شد",
                        PreviousStatus = c.IsActive,
                        CurrentStatus = status
                    });
                });
                db.SaveChanges();
            }
            catch (Exception e)
            {
                string errors = _errors.HandleError(e, Debugger.Info());
                TempData["Toastr"] = new ToastrViewModel() { Class = "warning", Text = $"خطایی پیش آمده{errors}" };
            }
            return RedirectToAction("GroupItemCards", new { id = id});
        }

    }
}

Attendance.Web/Views/CardGroupItems/AddSubGroup.cshtml
@model Attendance.Models.Entities.CardGroupItem

@{
    ViewBag.Title = "افزودن " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>افزودن @Html.DisplayNameFor(model => model)</h2>

@using (Html.BeginForm("Create", "CardGroupItems",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        @Html.ValidationSummary(true)

        <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Title)

                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ParentGroupId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParentGroupId")
                @Html.ValidationMessageFor(model => model.ParentGroupId)
            </div>
        </div>

        <div class="form-group">
			<div class="col-md-2">
            </div>
            <div class="col-md-10">
                    @Html.EditorFor(model => model.IsActive) 
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)

                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ایجاد" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
        </div>
</div>
}

Attendance.Web/Views/CardGroupItems/Create.cshtml
@model Attendance.Models.Entities.CardGroupItem

@{
    ViewBag.Title = "افزودن " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>افزودن @Html.DisplayNameFor(model => model)</h2>

@using (Html.BeginForm("Create", "CardGroupItems", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            <div class="form-group">
                @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title)

                    @Html.ValidationMessageFor(model => model.Title)
                </div>
            </div>

            <div class="form-group" hidden>
                @Html.LabelFor(model => model.GroupId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("GroupId")
                    @Html.ValidationMessageFor(model => model.GroupId)
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-2">
                </div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IsActive)

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)

                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>

            <div class="form-group" id="buttons">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="ایجاد" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

Attendance.Web/Views/CardGroupItems/Delete.cshtml
@model Attendance.Models.Entities.CardGroupItem

@{
    ViewBag.Title = "حذف " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>آیا از حذف این مورد اطمینان دارید؟</h3>
<div>    
    <hr />
    <div class="form-horizontal">        
    
         <div class="form-group">
            @Html.LabelFor(model => model.Group.Title, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Group.Title)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Title)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.IsActive)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CreationDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.LastModifiedDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Description)
      </div></div>

  </div>  

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

       <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="تایید حذف" class="btn btn-primary" /> 
            </div>
        </div>
    }
</div>

Attendance.Web/Views/CardGroupItems/Details.cshtml
@model Attendance.Models.Entities.CardGroupItem

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CardGroupItem</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Group.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id })  
</p>

Attendance.Web/Views/CardGroupItems/Edit.cshtml
@model Attendance.Models.Entities.CardGroupItem

@{
    ViewBag.Title = "ویرایش " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "CardGroupItems",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.GroupId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GroupId" )
                @Html.ValidationMessageFor(model => model.GroupId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.IsActive) 
            </div>
        </div>

	 @Html.HiddenFor(model => model.CreationDate)
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-primary" /> 
            </div>
        </div>
    </div>
}

Attendance.Web/Views/CardGroupItems/GroupItemCards.cshtml
@model IEnumerable<Attendance.Models.Entities.Card>
@using Attendance.Core.Enums
@{
    ViewBag.Title = "فهرست کارت ها";

    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}
 
<h4>همه کارت های موجود در @ViewBag.cardGroupTitle</h4>
@(Html.Kendo().Grid(Model)
        .Name("Grid")
        .Columns(columns =>
        {
        columns.Bound(model => model.DisplayCode);
        columns.Bound(model => model.Driver.FirstName);
        columns.Bound(model => model.Driver.LastName);
        columns.Bound(model => model.Driver.NationalCode);
        columns.Bound(model => model.Code);
		columns.Bound(item => @item.Id).Title("روز").Filterable(false).Groupable(false)
                      .Template(@<text>	@item.Day.GetDisplayName()</text>).Width(200);
        columns.Bound(model => model.IsActive);

        columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
                      .Template(@<text>
									@Html.ActionLink("ویرایش", "Edit","cards", new {id = @item.Id}, new {@class = "k-button"})
									@Html.ActionLink("حذف", "Delete", "cards", new {id = @item.Id}, new {@class = "k-button"})
									@Html.ActionLink("دسته بندی", "Group", "cards", new {id = @item.Id}, new {@class = "k-button"})
                                    <a class="k-button" href="/cards/status?id=@item.Id">@(item.IsActive?"غیرفعالسازی":"فعالسازی")</a>
									@Html.ActionLink("ورود و خروج", "Index", "CardLoginHistories", new { cardId = @item.Id}, new {@class = "k-button"})
									@*@Html.ActionLink("تعیین روزهای مجاز", "Index","CardDays", new {id = @item.Id}, new {@class = "k-button"})*@
							           </text>).Width(200);
        })
        .ToolBar(toolbar =>
        {
            toolbar.Custom().Action("CardStatus", "CardGroupItems", new { itemId = ViewBag.cardGroupItemId , status = false })
             .HtmlAttributes(new { @class = "font-medium text-danger" })
            .Text("غیرفعالسازی همه");
            toolbar.Custom().Action("CardStatus", "CardGroupItems", new { itemId = ViewBag.cardGroupItemId, status = true })
             .HtmlAttributes(new { @class = "font-medium text-danger" })
            .Text("فعالسازی همه");
            
        }
        )
        .Sortable(sortable => sortable.SortMode(GridSortMode.SingleColumn))
        .Filterable(filterable => filterable.Extra(false).Operators(o=>o.ForString(fs=>fs.StartsWith("شروع با").Contains("شامل")
        .EndsWith("اتمام با").IsEqualTo("برابر"))))
        .DataSource(dataSource => dataSource
                                    .Server()

                                    .Model(model => model.Id(item => item.Id))
                    )
    )

Attendance.Web/Views/CardGroupItems/Index.cshtml
@model IEnumerable<Attendance.Models.Entities.CardGroupItem>

@{
    ViewBag.Title = "فهرست ";

    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@(Html.Kendo().Grid(Model)
      .Name("Grid")
      .Columns(columns =>
      {
      columns.Bound(model => model.Id).Title("ردیف");
      columns.Bound(item => @item.Id).Title("گروه").Filterable(false).Groupable(false)
              .Template(@<a href="/cardgroups/index?id=@item.GroupId">	@item.Group.Title</a>).Width(200);
        columns.Bound(model => model.Title);
        columns.Bound(model => model.IsActive);
        columns.Bound(item => @item.Id).Title("تاریخ").Filterable(false).Groupable(false)
                      .Template(@<text>	@item.CreationDate.ToShamsi('s')</text>).Width(200);
					columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
									@Html.ActionLink("مشاهده کارت ها", "GroupItemCards", new {id = @item.Id}, new {@class = "k-button"})
									@Html.ActionLink("ویرایش", "Edit", new {id = @item.Id}, new {@class = "k-button"})
									@Html.ActionLink("حذف", "Delete", new {id = @item.Id}, new {@class = "k-button"}) 
									</text>).Width(200);
                  })
        .ToolBar(toolbar =>
        {
            toolbar.Custom().Action("Create","CardGroupItems",new { groupId = ViewBag.GroupId }).Text("افزودن");
        }
        )
        .HtmlAttributes(new { id = "tbl" })
        .DataSource(dataSource => dataSource
                                    .Server()

                                    .Model(model => model.Id(item => item.Id))
                    )
    )
<script>
    console.log($('#tbl'))
    var counter = 1;
    $('#tbl tr').each(function (index,key) {
        if (index!= 0) {
            console.log($(this.cells)[0])
            $(this.cells)[0].innerText = counter
            counter = counter + 1;
        }
    });
</script>