Attendance.Web/Controllers/WalkingLoginHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Attendance.Models;
using Attendance.Models.Entities;

namespace Attendance.Web.Controllers
{
    public class WalkingLoginHistoriesController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: WalkingLoginHistories
        public ActionResult Index(Guid? cardId)
        {
            ViewBag.cardId = cardId;
            if (cardId.HasValue)
            {
                var card = db.Cards.Find(cardId);
                if (card != null)
                    ViewBag.Title = "تاریخچه ورود و خروج کارت شماره " + card.DisplayCode;
                var walkingLoginHistories = db.WalkingLoginHistories.
                   Where(w => w.IsDeleted == false && w.CardId == cardId).OrderByDescending(w => w.CreationDate);
                return View(walkingLoginHistories.ToList());
            } 
            else
            {
                ViewBag.Title = "تاریخچه ورود و خروج کارت  ";
                var walkingLoginHistories = db.WalkingLoginHistories.Include(x=>x.Card).
                   Where(w => w.IsDeleted == false).OrderByDescending(w => w.CreationDate);
                return View(walkingLoginHistories.ToList());
            }
        }


        public ActionResult Create(Guid id)
        {
            ViewBag.cardId = id;
            return View(new WalkingLoginHistory() { 
            CardId = id
            });
        }

        // POST: WalkingLoginHistories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WalkingLoginHistory walkingLoginHistory)
        {
            if (ModelState.IsValid)
            {
                var card= db.Cards.Find(walkingLoginHistory.CardId);
                walkingLoginHistory.IsDeleted = false;
                walkingLoginHistory.CreationDate = DateTime.Now;
                walkingLoginHistory.CardId = walkingLoginHistory.CardId;
                walkingLoginHistory.Id = Guid.NewGuid();
                walkingLoginHistory.Card = card;

                db.WalkingLoginHistories.Add(walkingLoginHistory);
                db.SaveChanges();
                return RedirectToAction("Index", new { cardId = walkingLoginHistory.CardId });
            }

            ViewBag.cardId = walkingLoginHistory.CardId;
            return View(walkingLoginHistory);
        }

        // GET: WalkingLoginHistories/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WalkingLoginHistory walkingLoginHistory = db.WalkingLoginHistories.Find(id);
            if (walkingLoginHistory == null)
            {
                return HttpNotFound();
            }
            ViewBag.cardId = walkingLoginHistory.CardId;
            return View(walkingLoginHistory);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(WalkingLoginHistory walkingLoginHistory)
        {
            if (ModelState.IsValid)
            {
                walkingLoginHistory.IsDeleted = false;
                walkingLoginHistory.LastModifiedDate = DateTime.Now;
                db.Entry(walkingLoginHistory).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index", new { cardId = walkingLoginHistory.CardId });
            }
            ViewBag.cardId = walkingLoginHistory.CardId;
            return View(walkingLoginHistory);
        }

        // GET: WalkingLoginHistories/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WalkingLoginHistory walkingLoginHistory = db.WalkingLoginHistories.Find(id);
            if (walkingLoginHistory == null)
            {
                return HttpNotFound();
            }
            ViewBag.cardId = walkingLoginHistory.CardId;
            return View(walkingLoginHistory);
        }

        // POST: WalkingLoginHistories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            WalkingLoginHistory walkingLoginHistory = db.WalkingLoginHistories.Find(id);
            walkingLoginHistory.IsDeleted = true;
            walkingLoginHistory.DeletionDate = DateTime.Now;

            db.SaveChanges();
            return RedirectToAction("Index"/*, new { cardId = walkingLoginHistory.CardId }*/);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Attendance.Web/Views/WalkingLoginHistories/Create.cshtml
@model Attendance.Models.Entities.WalkingLoginHistory

@{
    ViewBag.Title = "افزودن " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>افزودن @Html.DisplayNameFor(model => model)</h2>

@using (Html.BeginForm("Create", "WalkingLoginHistories",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x=>x.CardId)
    <div class="form-horizontal">        
        @Html.ValidationSummary(true)

        <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(model => model.WalkingLoginHistoryType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.WalkingLoginHistoryType)

                @Html.ValidationMessageFor(model => model.WalkingLoginHistoryType)
            </div>
        </div>

        

        <div class="form-group">
			<div class="col-md-2">
            </div>
            <div class="col-md-10">
                    @Html.EditorFor(model => model.IsDriver)
                 
                @Html.ValidationMessageFor(model => model.IsDriver)
            </div>
        </div>

        <div class="form-group">
			<div class="col-md-2">
            </div>
            <div class="col-md-10">
                    @Html.EditorFor(model => model.IsDriverHelper)
                 
                @Html.ValidationMessageFor(model => model.IsDriverHelper)
            </div>
        </div>

        <div class="form-group">
			<div class="col-md-2">
            </div>
            <div class="col-md-10">
                    @Html.EditorFor(model => model.IsActive)
                 
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)

                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ایجاد" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index",new{id=ViewBag.CardLoginHistoryId })
            </div>
        </div>
        </div>
</div>
}

Attendance.Web/Views/WalkingLoginHistories/Delete.cshtml
@model Attendance.Models.Entities.WalkingLoginHistory

@{
    ViewBag.Title = "حذف " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>آیا از حذف این مورد اطمینان دارید؟</h3>
<div>    
    <hr />
    <div class="form-horizontal">        
    
         <div class="form-group">
            @Html.LabelFor(model => model.Card.DisplayCode, new { @class = "control-label col-md-2" })
        <div class="col-md-10 font-medium">
            @Html.DisplayFor(model => model.Card.DisplayCode)
      </div></div>
         <div class="form-group">
            @Html.LabelFor(model => model.WalkingLoginHistoryType, new { @class = "control-label col-md-2" })
        <div class="col-md-10 font-medium">
            @Html.DisplayFor(model => model.WalkingLoginHistoryType)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsDriver, new { @class = "control-label col-md-2" })
        <div class="col-md-10 font-medium">
            @Html.DisplayFor(model => model.IsDriver)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsDriverHelper, new { @class = "control-label col-md-2" })
        <div class="col-md-10 font-medium">
            @Html.DisplayFor(model => model.IsDriverHelper)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
        <div class="col-md-10 font-medium">
            @Html.DisplayFor(model => model.IsActive)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10 font-medium">
           @Model.CreationDate.ToShamsi('s')
      </div></div>
         
         <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10 font-medium">
            @Html.DisplayFor(model => model.Description)
      </div></div>

  </div>  

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

       <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="تایید حذف" class="btn btn-primary font-medium" />
		 
            </div>
        </div>
    }
</div>

Attendance.Web/Views/WalkingLoginHistories/Details.cshtml
@model Attendance.Models.Entities.WalkingLoginHistory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>WalkingLoginHistory</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CardLoginHistory.DriverName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardLoginHistory.DriverName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WalkingLoginHistoryType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WalkingLoginHistoryType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDriver)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDriver)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDriverHelper)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDriverHelper)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Attendance.Web/Views/WalkingLoginHistories/Edit.cshtml
@model Attendance.Models.Entities.WalkingLoginHistory

@{
	ViewBag.Title = "ویرایش " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
	Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "WalkingLoginHistories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true)
		@Html.HiddenFor(model => model.Id)
		@Html.HiddenFor(model => model.CardId)

		<div class="form-group">
			@Html.LabelFor(model => model.WalkingLoginHistoryType, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EnumDropDownListFor(model => model.WalkingLoginHistoryType)
				@Html.ValidationMessageFor(model => model.WalkingLoginHistoryType)
			</div>
		</div>


		<div class="form-group">
			@Html.LabelFor(model => model.IsDriver, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.IsDriver)
				@Html.ValidationMessageFor(model => model.IsDriver)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.IsDriverHelper, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.IsDriverHelper)
				@Html.ValidationMessageFor(model => model.IsDriverHelper)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.IsActive)
				@Html.ValidationMessageFor(model => model.IsActive)
			</div>
		</div>

		@Html.HiddenFor(model => model.CreationDate)
		<div class="form-group">
			@Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Description)
				@Html.ValidationMessageFor(model => model.Description)
			</div>
		</div>

		<div class="form-group" id="buttons">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="ثبت" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index", new { id = ViewBag.CardLoginHistoryId })
			</div>
		</div>
	</div>
}

Attendance.Web/Views/WalkingLoginHistories/Index.cshtml
@model IEnumerable<Attendance.Models.Entities.WalkingLoginHistory>

@{
    //ViewBag.Title = "تاریخچه ورود و خروج پیاده ";

    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@(Html.Kendo().Grid(Model)
                    .Name("Grid")
                    .Columns(columns =>
                    {
                    columns.Bound(model => model.Card.DisplayCode);
                    columns.Bound(model => model.WalkingLoginHistoryTypeStr);
                    columns.Bound(model => model.IsDriver);
                    columns.Bound(model => model.IsDriverHelper);
              //columns.Bound(model => model.IsActive);
              columns.Bound(item => @item.Id).Title("تاریخ").Filterable(false).Groupable(false)
                                  .Template(@<text>	@item.CreationDate.ToShamsi('s')</text>).Width(200);
					columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
									@Html.ActionLink("ویرایش", "Edit", new {id = @item.Id}, new {@class = "k-button"})
									@Html.ActionLink("حذف", "Delete", new {id = @item.Id}, new {@class = "k-button"})
									</text>).Width(200);
                    })
        .ToolBar(toolbar =>
        {
            if (ViewBag.cardId != null)
            {
                toolbar.Custom().Action("Create", "WalkingLoginHistories",new { id = ViewBag.cardId}).Text("افزودن");
            }
        }
        )
                .Sortable(sortable => sortable.SortMode(GridSortMode.SingleColumn))
        .Filterable(filterable => filterable.Extra(false).Operators(o => o.ForString(fs => fs.StartsWith("شروع با").Contains("شامل")
          .EndsWith("اتمام با").IsEqualTo("برابر"))))
        .DataSource(dataSource => dataSource
                                    .Server()

                                    .Model(model => model.Id(item => item.Id))
                    )
    )