Attendance.Web/Controllers/LoginHistoryToolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Attendance.Models;
using Attendance.Models.Entities;

namespace Attendance.Web.Controllers
{
    public class LoginHistoryToolsController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: LoginHistoryTools
        public ActionResult Index()
        {
            var loginHistoryTools = db.LoginHistoryTools.Include(l => l.CardLoginHistory).Where(l=>l.IsDeleted==false).OrderByDescending(l=>l.CreationDate).Include(l => l.Tools).Where(l=>l.IsDeleted==false).OrderByDescending(l=>l.CreationDate).Include(l => l.Units).Where(l=>l.IsDeleted==false).OrderByDescending(l=>l.CreationDate);
            return View(loginHistoryTools.ToList());
        }

        // GET: LoginHistoryTools/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoginHistoryTool loginHistoryTool = db.LoginHistoryTools.Find(id);
            if (loginHistoryTool == null)
            {
                return HttpNotFound();
            }
            return View(loginHistoryTool);
        }

        // GET: LoginHistoryTools/Create
        public ActionResult Create(Guid id)
        {
            ViewBag.CardLoginHistoryId = new SelectList(db.CardLoginHistories.Where(x=>x.Id==id).ToList().Select(x=>new { Id = x.Id , Title = $"کارت:{x.Card.DisplayCode} - {x.LoginDate.ToShamsi('s')}"}), "Id", "Title",id);
            ViewBag.ToolId = new SelectList(db.Tools, "Id", "Title");
            ViewBag.UnitId = new SelectList(db.Units, "Id", "Title");
            ViewBag.LastLogins = db.LoginHistoryTools.Where(x => x.CardLoginHistoryId == id).Select(x=>new LoginToolViewModel (){ Tool = x.Tools.Title,Unit=x.Units.Title,Amount=x.Amount??0}).ToList();
            return PartialView();
        }

        // POST: LoginHistoryTools/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CardLoginHistoryId,ToolId,UnitId,Amount,IsActive,CreationDate,LastModifiedDate,IsDeleted,DeletionDate,Description")] LoginHistoryTool loginHistoryTool)
        {
            if (ModelState.IsValid)
            {
				loginHistoryTool.IsDeleted=false;
				loginHistoryTool.CreationDate= DateTime.Now; 
					
                loginHistoryTool.Id = Guid.NewGuid();
                db.LoginHistoryTools.Add(loginHistoryTool);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CardLoginHistoryId = new SelectList(db.CardLoginHistories.ToList().Select(x => new { Id = x.Id, Title = $"کارت:{x.Card.DisplayCode} - {x.LoginDate.ToShamsi('s')}" }), "Id", "Title");
            ViewBag.ToolId = new SelectList(db.Tools, "Id", "Title", loginHistoryTool.ToolId);
            ViewBag.UnitId = new SelectList(db.Units, "Id", "Title", loginHistoryTool.UnitId);
            return View(loginHistoryTool);
        }

        // GET: LoginHistoryTools/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoginHistoryTool loginHistoryTool = db.LoginHistoryTools.Find(id);
            if (loginHistoryTool == null)
            {
                return HttpNotFound();
            }
            ViewBag.CardLoginHistoryId = new SelectList(db.CardLoginHistories.ToList().Select(x => new { Id = x.Id, Title = $"کارت:{x.Card.DisplayCode} - {x.LoginDate.ToShamsi('s')}" }), "Id", "Title", loginHistoryTool.CardLoginHistoryId);
            ViewBag.ToolId = new SelectList(db.Tools, "Id", "Title", loginHistoryTool.ToolId);
            ViewBag.UnitId = new SelectList(db.Units, "Id", "Title", loginHistoryTool.UnitId);
            return View(loginHistoryTool);
        }

        // POST: LoginHistoryTools/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CardLoginHistoryId,ToolId,UnitId,Amount,IsActive,CreationDate,LastModifiedDate,IsDeleted,DeletionDate,Description")] LoginHistoryTool loginHistoryTool)
        {
            if (ModelState.IsValid)
            {
				loginHistoryTool.IsDeleted=false;
					loginHistoryTool.LastModifiedDate=DateTime.Now;
                db.Entry(loginHistoryTool).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CardLoginHistoryId = new SelectList(db.CardLoginHistories, "Id", "DriverName", loginHistoryTool.CardLoginHistoryId);
            ViewBag.ToolId = new SelectList(db.Tools, "Id", "Title", loginHistoryTool.ToolId);
            ViewBag.UnitId = new SelectList(db.Units, "Id", "Title", loginHistoryTool.UnitId);
            return View(loginHistoryTool);
        }

        // GET: LoginHistoryTools/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoginHistoryTool loginHistoryTool = db.LoginHistoryTools.Find(id);
            if (loginHistoryTool == null)
            {
                return HttpNotFound();
            }
            return View(loginHistoryTool);
        }

        // POST: LoginHistoryTools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            LoginHistoryTool loginHistoryTool = db.LoginHistoryTools.Find(id);
			loginHistoryTool.IsDeleted=true;
			loginHistoryTool.DeletionDate=DateTime.Now;
 
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Attendance.Web/Views/LoginHistoryTools/Create.cshtml
@model Attendance.Models.Entities.LoginHistoryTool
@using Attendance.Models.Entities;
@{
    ViewBag.Title = "افزودن " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    //Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
    Layout = null;
}
@Html.Label("موارد" , new { @class = "control-label" })
 
<div class="form-group k-form border">
    <div class="form-group">
        <table class="table table-responsive">

        @foreach (var item in (List<LoginToolViewModel>)ViewBag.LastLogins)
        {
            <tr>
                <td>@item.Tool</td>
                <td>@item.Unit</td>
                <td>@item.Amount</td>
            </tr>
        }
        </table>
    </div>

    <div class="form-group" hidden>
        @Html.LabelFor(model => model.CardLoginHistoryId, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CardLoginHistoryId")
            @Html.ValidationMessageFor(model => model.CardLoginHistoryId)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ToolId, new { @class = "control-label col-md-1" })
        <div class="col-md-3">
            @Html.DropDownList("ToolId","")
            @Html.ValidationMessageFor(model => model.ToolId)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UnitId, new { @class = "control-label col-md-1" })
        <div class="col-md-3">
            @Html.DropDownList("UnitId","")
            @Html.ValidationMessageFor(model => model.UnitId)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Amount, new { @class = "control-label col-md-1" })
        <div class="col-md-3">
            @Html.EditorFor(model => model.Amount)

            @Html.ValidationMessageFor(model => model.Amount)
        </div>
    </div>
</div>

Attendance.Web/Views/LoginHistoryTools/Delete.cshtml
@model Attendance.Models.Entities.LoginHistoryTool

@{
    ViewBag.Title = "حذف " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>آیا از حذف این مورد اطمینان دارید؟</h3>
<div>    
    <hr />
    <div class="form-horizontal">        
    
         <div class="form-group">
            @Html.LabelFor(model => model.CardLoginHistory.DriverName, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CardLoginHistory.DriverName)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Tools.Title, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Tools.Title)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Units.Title, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Units.Title)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Amount, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Amount)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.IsActive)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CreationDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.LastModifiedDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Description)
      </div></div>

  </div>  

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

       <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="تایید حذف" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
    }
</div>

Attendance.Web/Views/LoginHistoryTools/Details.cshtml
@model Attendance.Models.Entities.LoginHistoryTool

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>LoginHistoryTool</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CardLoginHistory.DriverName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardLoginHistory.DriverName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tools.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tools.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Units.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Units.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Attendance.Web/Views/LoginHistoryTools/Edit.cshtml
@model Attendance.Models.Entities.LoginHistoryTool

@{
    ViewBag.Title = "ویرایش " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "LoginHistoryTools",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CardLoginHistoryId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CardLoginHistoryId", String.Empty)
                @Html.ValidationMessageFor(model => model.CardLoginHistoryId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToolId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ToolId", String.Empty)
                @Html.ValidationMessageFor(model => model.ToolId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UnitId", String.Empty)
                @Html.ValidationMessageFor(model => model.UnitId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                                  @Html.EditorFor(model => model.Amount)
                @Html.ValidationMessageFor(model => model.Amount)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

	 @Html.HiddenFor(model => model.CreationDate)
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
    </div>
}

Attendance.Web/Views/LoginHistoryTools/Index.cshtml
@model IEnumerable<Attendance.Models.Entities.LoginHistoryTool>

@{
    ViewBag.Title = "فهرست ";

    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@(Html.Kendo().Grid(Model)
              .Name("Grid")
              .Columns(columns =>
                  {
		columns.Bound(model => model.CardLoginHistory.Card.DisplayCode);
        columns.Bound(model => model.Tools.Title);
        columns.Bound(model => model.Units.Title);
        columns.Bound(model => model.Amount);
        columns.Bound(model => model.IsActive);
         columns.Bound(item => @item.Id).Title("تاریخ").Filterable(false).Groupable(false)
                      .Template(@<text>	@item.CreationDate.ToShamsi('s')</text>).Width(200);
					columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
									@Html.ActionLink("ویرایش", "Edit", new {id = @item.Id}, new {@class = "k-button"})
									@Html.ActionLink("حذف", "Delete", new {id = @item.Id}, new {@class = "k-button"})
									</text>).Width(200);
		}) 
		.DataSource(dataSource => dataSource
									.Server()

									.Model(model => model.Id(item => item.Id))
					)
	)